# Generated by Django 5.1.5 on 2025-01-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_invoice_id_addresses_invoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
