# Generated by Django 5.1.5 on 2025-01-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_orders_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='integrations',
        ),
        migrations.AddField(
            model_name='integrations',
            name='apiurl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integrations',
            name='apikey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
