# Generated by Django 5.1.5 on 2025-01-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_remove_orderstatus_integrations_integrations_apiurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershippings',
            name='deliverydate',
        ),
        migrations.AddField(
            model_name='orderproductsordershippings',
            name='receiveddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproductsordershippings',
            name='shipped_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
