# Generated by Django 5.1.5 on 2025-01-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_addresses_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='integrations',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='logistics',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaces',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ordershippings',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productprices',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
