# Generated by Django 5.1.5 on 2025-01-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_addresses_title_alter_categories_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='carriercode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
