# Generated by Django 5.1.5 on 2025-01-20 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_addresses_city_alter_addresses_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='invoices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.invoices'),
        ),
    ]
