# Generated by Django 5.1.5 on 2025-01-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='paymentdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
