# Generated by Django 5.1.5 on 2025-01-20 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_alter_orders_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.products'),
        ),
    ]
