# Generated by Django 5.1.5 on 2025-01-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_alter_orderproducts_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='image1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
