MAPPING = {
    "tiendamiaus": {
        "order_id": "integrationorderid",
        "commercial_id": "title",
        "order_state": "integrationstatus",
        "currency_iso_code": "currency",
        "created_date": "purchase_date",
        "delivery_date.latest": "latestdelivery_date",
        "delivery_date.earliest": "earliestdelivery_date",
        "total_price": "totalprice",
        "total_commission": "totalcomission",
        "customer.customer_id": "integrationcustomerid",
        "customer.firstname": "firstname",
        "customer.lastname": "lastname",
        "shipping_carrier_code": "carriercode",
        "shipping_tracking": "tracking",
        "shipping_tracking_url": "tracking_url",
        "shipping_price": "shippingprice",
        "order_lines.product_sku": "sku",
        "order_lines.price_unit": "price",
        "order_lines.quantity": "quantity",
        "order_lines.product_medias[0].media_url": "image1",
    },
    "worten": {
        "id": "integrationorderid",
        "reference": "title",
        "status": "integrationstatus",
        "currency": "currency",
        "created_at": "purchase_date",
        "expected_delivery.max": "latestdelivery_date",
        "expected_delivery.min": "earliestdelivery_date",
        "total_amount": "totalprice",
        "commission_fee": "totalcomission",
        "buyer.id": "integrationcustomerid",
        "buyer.name": "firstname",
        "buyer.surname": "lastname",
        "carrier": "carriercode",
        "tracking_number": "tracking",
        "tracking_link": "tracking_url",
        "shipping_cost": "shippingprice",
        "items.sku": "sku",
        "items.unit_price": "price",
        "items.quantity": "quantity",
        "items.images[0].url": "image1",
    }
}